### ISSUE TITLE
/02_lakasminoseg_energiaszegenyseg/02_01_barchart.html

### ISSUE THREAD

**Issue by zolizoli** [mandarin-data/test_vizs#17]
Mit csinál a "Rendezés" gomb? Csak én vagyok béna, mert én nem tudomtam olyan állapotba hozni a gombot, hogy nyomkodni lehessen :( Illetve, kell az nekünk oda????

**Comment by sdfghjklbn** [comment]
A rendezés gomb csak akkor aktivizálódik ha valamelyik kategóriára leszűrsz (kattintás legendre), aztán csökkenő sorrendbe rendez az adott kategória szerint. Szerintem ártani nem árt, de ha feleslegesnek érzitek ki lehet venni, vagy megpróbálhatom invisiblie-é tenni a gombot és a hozzá tartozó feliratot míg nincs haszna.
